version: "3.5"
# volumes:
#   vhosts:
#     mountpoint: ./
services:

  nginx:
    container_name: nginx
    image: nginxproxy/nginx-proxy
    restart: unless-stopped
    labels: 
      - com.github.nginx-proxy.nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost:/etc/nginx/vhost.d
    logging:
      options:
          max-size: "10m"
          max-file: "3"

  letsencrypt-companion:
    container_name: letsencrypt-companion
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost:/etc/nginx/vhost.d
      - ./nginx/acme:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: ropnom5291@gmail.com
      NGINX_PROXY_CONTAINER: nginx

  hello-world:
    container_name: hello-world
    image: kornkitti/express-hello-world
    expose:
      - "8080"
    environment:
      VIRTUAL_HOST: test.programing.es
      LETSENCRYPT_HOST: test.programing.es